// stubs/inertia-vue/resources/js/Components/TextInput.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';

// ts-begin
defineProps<{
    modelValue: string;
}>();
// ts-end
// js-begin
defineProps({
    modelValue: {
        type: String,
        required: true,
    },
});
// js-end

defineEmits(['update:modelValue']);

const input = ref/* ts-begin */<HTMLInputElement>/* ts-end */();

onMounted(() => {
    if (input.value?.hasAttribute('autofocus')) {
        input.value?.focus();
    }
});

defineExpose({ focus: () => input.value?.focus() });
</script>

<template>
    <input
        class="border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm"
        :value="modelValue"
        @input="$emit('update:modelValue', /* ts-begin */(/* ts-end */$event.target/* ts-begin */ as HTMLInputElement)/* ts-end */.value)"
        ref="input"
    />
</template>

// stubs/inertia-react/resources/js/Components/TextInput.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef/* ts-begin */, InputHTMLAttributes/* ts-end */ } from 'react';

export default forwardRef(function TextInput(
    { type = 'text', className = '', isFocused = false, ...props }/* ts-begin */: InputHTMLAttributes<HTMLInputElement> & { isFocused?: boolean }/* ts-end */,
    ref
) {
    const localRef = useRef/* ts-begin */<HTMLInputElement>/* ts-end */(null);

    useImperativeHandle(ref, () => ({
        focus: () => localRef.current?.focus(),
    }));

    useEffect(() => {
        if (isFocused) {
            localRef.current?.focus();
        }
    }, []);

    return (
        <input
            {...props}
            type={type}
            className={
                'border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm ' +
                className
            }
            ref={localRef}
        />
    );
});
