// stubs/inertia-react/resources/js/Components/Checkbox.tsx
import { InputHTMLAttributes } from 'react'; // ts-only
// ts-only
export default function Checkbox({ className = '', ...props }/* ts-begin */: InputHTMLAttributes<HTMLInputElement>/* ts-end */) {
    return (
        <input
            {...props}
            type="checkbox"
            className={
                'rounded dark:bg-gray-900 border-gray-300 dark:border-gray-700 text-indigo-600 shadow-sm focus:ring-indigo-500 dark:focus:ring-indigo-600 dark:focus:ring-offset-gray-800 ' +
                className
            }
        />
    );
}

// stubs/inertia-vue/resources/js/Components/Checkbox.vue
<script setup lang="ts">
import { computed } from 'vue';

const emit = defineEmits(['update:checked']);

// ts-begin
const props = defineProps<{
    checked: boolean;
    value?: any;
}>();
// ts-end
// js-begin
const props = defineProps({
    checked: {
        type: [Array, Boolean],
        required: true,
    },
    value: {
        default: null,
    },
});
// js-end

const proxyChecked = computed({
    get() {
        return props.checked;
    },

    set(val) {
        emit('update:checked', val);
    },
});
</script>

<template>
    <input
        type="checkbox"
        :value="value"
        v-model="proxyChecked"
        class="rounded dark:bg-gray-900 border-gray-300 dark:border-gray-700 text-indigo-600 shadow-sm focus:ring-indigo-500 dark:focus:ring-indigo-600 dark:focus:ring-offset-gray-800"
    />
</template>
