// stubs/inertia-react/resources/js/Components/InputLabel.tsx
import { LabelHTMLAttributes } from 'react'; // ts-only
// ts-only
export default function InputLabel({ value, className = '', children, ...props }/* ts-begin */: LabelHTMLAttributes<HTMLLabelElement> & { value?: string }/* ts-end */) {
    return (
        <label {...props} className={`block font-medium text-sm text-gray-700 dark:text-gray-300 ` + className}>
            {value ? value : children}
        </label>
    );
}

// stubs/inertia-vue/resources/js/Components/InputLabel.vue
<script setup lang="ts">
// ts-begin
defineProps<{
    value?: string;
}>();
// ts-end
// js-begin
defineProps({
    value: {
        type: String,
    },
});
// js-end
</script>

<template>
    <label class="block font-medium text-sm text-gray-700 dark:text-gray-300">
        <span v-if="value">{{ value }}</span>
        <span v-else><slot /></span>
    </label>
</template>
