// stubs/inertia-react/resources/js/Components/InputError.tsx
import { HTMLAttributes } from 'react'; // ts-only
// ts-only
export default function InputError({ message, className = '', ...props }/* ts-begin */: HTMLAttributes<HTMLParagraphElement> & { message?: string }/* ts-end */) {
    return message ? (
        <p {...props} className={'text-sm text-red-600 dark:text-red-400 ' + className}>
            {message}
        </p>
    ) : null;
}

// stubs/inertia-vue/resources/js/Components/InputError.vue
<script setup lang="ts">
// ts-begin
defineProps<{
    message?: string;
}>();
// ts-end
// js-begin
defineProps({
    message: {
        type: String,
    },
});
// js-end
</script>

<template>
    <div v-show="message">
        <p class="text-sm text-red-600 dark:text-red-400">
            {{ message }}
        </p>
    </div>
</template>
